# Название нашего автоматического процесса
name: Deploy to Production VPS

on:
  # Условие запуска: любой пуш в основную ветку 'main'
  # Если ваша основная ветка называется 'master', замените 'main' на 'master'
  push:
    branches: [ "main" ]

jobs:
  # Название нашей единственной задачи
  deploy:
    # Запускать на стандартной виртуальной машине от GitHub
    runs-on: ubuntu-latest

    steps:
    # Название шага
    - name: Deploy to VPS via SSH
      # Используем готовое действие для подключения по SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        # Используем секреты, которые вы добавите в настройки GitHub
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        # Скрипт, который нужно выполнить на сервере
        script: |
          cd ~/FlameWall
          git pull
          git submodule update --init --remote --merge
          docker compose -f docker-compose.prod.yml up --build -d --remove-orphans
          echo "Deployment to VPS completed successfully!"